spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: avro-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    properties:
      schema.registry.url: http://localhost:8081
    listener: # listener-container of Spring Kafka
      ack-mode: MANUAL_IMMEDIATE # on acknowldege() being called on the Acknowledge object "immediately" commit offset
      syncCommits: false # enable async commits for the container